import type { Metadata } from "next";
import { Geist, Geist_Mono, Hind } from "next/font/google"; // Added Hind
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hind = Hind({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "devanagari"], // Added devanagari for Hindi support
  variable: "--font-hind",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hind.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
